name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Remove icon references from index.html
        run: |
          sed -i '/favicon-128x128.png/d' index.html
          sed -i '/favicon-96x96.png/d' index.html
          sed -i '/favicon-32x32.png/d' index.html
          sed -i '/favicon-16x16.png/d' index.html
          sed -i '/favicon.ico/d' index.html
          
      - name: Build SPA
        run: npm run build:spa
        
      - name: Create release archive
        run: |
          cd dist/spa
          zip -r ../../myuipro-spa-${{ github.ref_name }}.zip .
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: myuipro-spa-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}